### ISSUE TITLE
Version for old Androids

### ISSUE THREAD

**Issue by rudolfmu** [woheller69/TimeLapseCamera#1]
Please make a version that runs on old Android versions. Your app could give old phones a new usage.

**Comment by woheller69** [comment]
You can try this, but I cannot promise that it works. I don't have such old devices.
I compiled the old version from Zeitgeist https://github.com/zeitgeist87/SpartanTimeLapseRecorder
(which I used as base for the development) for minSDK 14.

[TimeLapseCam_MinSdK14.apk.zip](https://github.com/woheller69/TimeLapseCamera/files/10174614/TimeLapseCam_MinSdK14.apk.zip)

Remove .zip before installing

**Comment by woheller69** [comment]
Did you try it?
