### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by jackthebean** [woheller69/TimeLapseCamera#12]
Just installed v1.2 of TLC from f-droid.  Installed and tried to use but nothing I do seems to take any photos.   

![Screenshot_20230402_090943_org woheller69 TimeLapseCam](https://user-images.githubusercontent.com/9907054/229342933-32f47a9d-e821-4ee3-b361-4660db450826.jpg)

I have tried to take using 'Start' instruction and the scheduled time feature and every time a TLC notification appears in the top status bar and with notification 'Recording is running' but then disappears after about 5 secs and although folders have been created in storage no files are ever created.

Phone is Honor View 20 running Android 10.

**Comment by woheller69** [comment]
What if you increase Stop recording after to infinity?

**Comment by jackthebean** [comment]
Thanks for quick response.
Now it starts and runs BUT:
1  With the timelapse video it stopped after a few shots the first time I ran it.  2nd time it rang seemingly fine until manual stop.
2  With time lapse images it stopped after 7 photos AND it took 1 and then another almost immediately then waited the set interval (4 secs) and then took another followed by another almost immediately and then so on.  But never took 8th photo and after ?20secs wait I manually stopped.
Hope this helps and great app.
Thanks,

**Comment by woheller69** [comment]
Maybe restart your phone. Maybe a timer is hanging

**Comment by jackthebean** [comment]
Restarted.
Time lapse images now did not stop after 7 shots and kept going till about 18 when I manually stopped.  But still taking 1 and then another after 1sec and then 4 sec wait before another one and 1 sec another and so on.
So still a bit odd but sort of working.
Did not try timelapse video again.
Maybe the next version will get rid of more intermittent bugs.........
Thanks,

**Comment by woheller69** [comment]
Try a shorter or longer interval. E.g  2s or 10s
For longer intervals the app uses a power saving timer.
Depending on the speed of your camera it may switch between these timers.

So far I cannot reproduce the problem.

**Comment by woheller69** [comment]
It also depends on the options for various delays
