### ISSUE TITLE
Compression options for videos

### ISSUE THREAD

**Issue by lumnn** [woheller69/TimeLapseCamera#13]
First of all - thanks for this great app!

Would it be possible to have some compression options for recorded video?

It's not end of the world, but ~2h recording of 1920p@30fps takes around 20GB space. I believe without loosing on quality I can optimize it with ffmpeg to ~2GB. I wonder whether that would be possible within the app as an option?

**Comment by woheller69** [comment]
this app uses  the Android Mediarecorder class:
available options are:

https://developer.android.com/reference/android/media/MediaRecorder.VideoEncoder

h264 is being used. As far as I know that has the best compression...

**Comment by lumnn** [comment]
I've used this command for reducing file size:

`ffmpeg -i test0.mp4 -vcodec libx265 -crf 28 test0_optim.mp4`

I believe this converts into HEVC, but CRF value may play also a part in file size.

Reading further on [MDN Video codec guide](https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Video_codecs) it looks like HEVC, AV1 and VP9 could potentially perform better than H264 (although I'm not 100% sure that I'm right here).

If that's not too much work, then I'd be soo much grateful for the options on codecs used

**Comment by woheller69** [comment]
I tried AV1 (which should be the best) but it only works starting with Android 13 - in theory. 
Practically it did not work at all on my Android 13 device...

But I added an option to set the video encoding bit rate. You can play around with that.
Please note that below a certain value (defined by the media codec) the bit rate is not further reduced.

Uninstall
Remove .zip and install

[app-release.apk.zip](https://github.com/woheller69/TimeLapseCamera/files/11423758/app-release.apk.zip)

**Comment by lumnn** [comment]
This is awesome! Setting it to 8000 makes the file size around 4 times smaller! (1080p@30fps)

I don't want to be picky, but the units are confusing. When entering for the first time it doesn't mention what unit the value needs to be. After entering it shows bit/s but the actual value I believe it is kilo bits per second

**Comment by woheller69** [comment]
it should be in bits/s. I don't think I used a factor of 1000 anywhere.

I (for me) will probaply only use 2 values.
0: best quality
1: smallest size

**Comment by woheller69** [comment]
Some small improvements
[app-release.apk.zip](https://github.com/woheller69/TimeLapseCamera/files/11428115/app-release.apk.zip)

**Comment by lumnn** [comment]
Looks great!

**Comment by woheller69** [comment]
-> V1.3
