### ISSUE TITLE
Remote access / control improvements

### ISSUE THREAD

**Issue by lumnn** [woheller69/TimeLapseCamera#14]
At the moment I'm using RustDesk app to preview and then start/stop recording, however I'm experiencing few problems, which could be perhaps improved in few ways.

1. I'm unable to tell recording is happening without connecting to the phone. Would it be possible to set-up optional camera flash / notification led to blink every X mins to indicate recording is enabled?
2. Start / Stop buttons are few steps away, which makes it more difficult to click on poor connection with remote control. I can think of few options that this could be improved:
    - If the start/stop could be extracted to main screen, it would be one tap less to control
    - A home screen widget for even less clicks?
    - An optional HTTP API that could be used remotely over the same WIFI network? Just for start/stop/status. I don't even necessarily need an UI/separate app for that, as I could create a simple HTML page for that could handle sending requests.

**Comment by woheller69** [comment]
unfortunately I did not manage to switch the notification LED on. No idea why...

**Comment by andreasb242** [comment]
Hi
@woheller69 I added you an example with blinking LED.
I noticed in the Pull how to allow to set the LED, at least on MIUI.

**Comment by woheller69** [comment]
Will have a lock next week. I had already tried setLights in the notification while ago, but it didn't work on my Samsung...

**Comment by woheller69** [comment]
Will have a lock next week. I had already tried setLights in the notification while ago, but it didn't work on my Samsung...

**Comment by andreasb242** [comment]
>Will have a lock next week. I had already tried setLights in the notification while ago, but it didn't work on my Samsung...
Sure. But it shows an additional notification, it's not possible else, and it's a bad solution.

I'll add a HTTP / REST Interface, and create another Pull, I think this is the solution. But I need some time for implementation.

**Comment by woheller69** [comment]
A REST interface for remote control?
Might be a cool thing :-)

**Comment by woheller69** [comment]
A REST interface for remote control?
Might be a cool thing :-)

**Comment by woheller69** [comment]
A REST interface for remote control?
Might be a cool thing :-)

**Comment by woheller69** [comment]
A REST interface for remote control?
Might be a cool thing :-)

**Comment by andreasb242** [comment]
This will be solved with the Pull https://github.com/woheller69/TimeLapseCamera/pull/30 if @woheller69 agrees ;-)
Additional I created this ticket:
https://github.com/woheller69/TimeLapseCamera/issues/31
