### ISSUE TITLE
Add option to write time and other information onto pictures

### ISSUE THREAD

**Issue by Kristjan-Ai** [woheller69/TimeLapseCamera#15]
The app would be much more powerful if there was a way to write the date, time and other info like battery percentage or other sensor data directly onto a taken picture as text. 
Exactly like in [this](https://github.com/dngames/mobilewebcam-android) app called mobilewebcam. I would use mobilewebcam if it could take pics in the background like this one can. It hasn't been updated for a long time too.
Or if you could point me to the piece of code where this can be implemented then I might even be able to do it myself, I can't code in java though.

**Comment by woheller69** [comment]
I am sorry, but I will not implement that. Everybody will want something else written on the pictures.
And I don't know how to do this either...
