### ISSUE TITLE
Feature request: preview in main window

### ISSUE THREAD

**Issue by psa-jforestier** [woheller69/TimeLapseCamera#16]
Hello.
Thank you for this app. I'm comparing it with an other well known time lapse option which crash on my old Sony (Android 6) phone, but your app is working well.

I'm using v1.3 published 2023-05-17 
It would be great if the pictures could be preview in live, directly from the main screen, so we can see how the "Select Camera", "Exposure comptensation", "Zoom" options are affecting the image. For now, the preview is on the "Open Preview" menu, but I have to open it, check for exposure, go back to main screen, change exposure , check again etc.

Also other improvement I would like to see on the preview window : exposure lock (#10) ; focus : auto, macro, manual, infinite ; a blink (notification led or in the main UI) each time a picture is recorded.

**Comment by woheller69** [comment]
I moved Start/Stop/Preview from the menu to the action bar.
So it is one step less.

Please try:
uninstall
remove .zip and install

[app-release.apk.zip](https://github.com/woheller69/TimeLapseCamera/files/11504846/app-release.apk.zip)
