### ISSUE TITLE
Scheduling not working when recording is set to stop a few minutes after start

### ISSUE THREAD

**Issue by YottaMxt** [woheller69/TimeLapseCamera#19]
Hello,

The scheduling and auto-stopping feature is nice, but if I need to capture a very precise moment and I set it to stop 1 or 2 minutes after record beginning, it just stops in a few seconds and the recording isn't saved to the gallery.

Thanks in advanced.

**Comment by woheller69** [comment]
for me it works.
Some Android devices have problems waking up from sleep mode.
What is your device and Android version?

**Comment by YottaMxt** [comment]
I have Android 12 with LineageOS 19, and I had the capture interval set to 15 secs if relevant.

**Comment by woheller69** [comment]
On my Android 12 / LineageOS it also works...

**Comment by woheller69** [comment]
maybe see also #12
