### ISSUE TITLE
Setting camera capture rate is painful

### ISSUE THREAD

**Issue by n21brown** [woheller69/TimeLapseCamera#2]
Having a slider that cant can hit anything from 1ms to 10 mins with no accuracy isnt good.

Try setting a timer to 30s. Youll be there for hours

**Comment by woheller69** [comment]
Please try this. I created my own time picker for it.
-Uninstall old version
-Remove .zip from filename
-Install

[app-release.apk.zip](https://github.com/woheller69/TimeLapseCamera/files/10184696/app-release.apk.zip)

**Comment by woheller69** [comment]
Have you tried the improved version?
