### ISSUE TITLE
Issue: Recording got limited to about 27minutes (3.8GB) of video

### ISSUE THREAD

**Issue by bdutta** [woheller69/TimeLapseCamera#25]
So, I installed TimeLapseCamera app (thru F-droid) on a old Realme 2 camera, to use it as an action camera to record a sunday morning motorcycle ride. I set the resolution to 1080p, standard video mode (not time-lapse mode), 30fps, +4 exposure etc. I had set the recording time 3hrs, because the ride one way was around 2:15hrs. When I stopped my motorcycle to stop the recording, I found the app showing the recording icon ON, i.e. I could hit the stop to stop it. I'd assumed that the full duration of the ride would have been recorded. On returning home and downloading the video to my PC, I found that while the size of the file was 3.8GB, the duration recorded was just around 27minutes. The phone definitely had around 40GB of storage to spare (so cannot be a case of filesystem running out of space), and phone battery had a solid 70% left too.

Would be nice if the app could be enhanced to run some on-demand diagnostics that could then be shared back when reporting issues. This is a pretty useful app, if it were to work fully as described. Diagnostics that share why last recording ended, any errors/warnings, storage space, battery status, camera API usage data, permission data etc.

**Comment by woheller69** [comment]
Probably your OS stopped the app in background. 

https://dontkillmyapp.com/

**Comment by bdutta** [comment]
That certainly explains it, as I had indeed setup battery saver mode for the ride.
