### ISSUE TITLE
Video unplayable if device switched off

### ISSUE THREAD

**Issue by hjek** [woheller69/TimeLapseCamera#26]
The video unplayable if the device is switched off while recording. To reproduce:

- start recording (in video mode)
- switch off device
- a non-empty but unplayable video file is written to disk

**Comment by woheller69** [comment]
You simply should not switch it off. If the file is corrupted it cannot be played of course.

**Comment by woheller69** [comment]
Probably there are players that still can play it or fix it

**Comment by hjek** [comment]
> You simply should not switch it off.

I agree, but please hear me out on the use case for this.

TimeLapseCam is the only camera app on F-Droid which can record in the background on recent Android versions. It is incredibly useful for photo journalism in hostile environments that an attacker can't just stop the recording by pressing the lock button (like they can with other camera apps).

However, because of this file corruption bug, an attacker can effectively delete the video recording on a locked phone by switching it off.

I understand that this use case may fall outside the scope of TimeLapseCam, but this app just happens to already be a lot more resilient than apps specifically designed for that use case, such as Tella.

**Comment by woheller69** [comment]
Please try this.
Uninstall
Remove .zip and install

I added a receiver for the shutdown signal. In this case the recording is stopped.

[app-release.apk.zip](https://github.com/woheller69/TimeLapseCamera/files/14733313/app-release.apk.zip)

**Comment by hjek** [comment]
Thanks a lot for giving it a look!

It didn't fix the issue.

> Probably there are players that still can play it or fix it

I'll look into this, but VLC and MPV won't show a single frame.

**Comment by woheller69** [comment]
on my test device it fixes the issue. I even can hear the sound that the video is stopped, like when pressing the stop button

**Comment by hjek** [comment]
Tested on another newer device, and the issue is fixed there. Ridiculously fast bug fix.

It's very helpful for us documenting to keep people safe. Thank you so much!
