### ISSUE TITLE
App stopping, and no status visible on main display

### ISSUE THREAD

**Issue by andreasb242** [woheller69/TimeLapseCamera#27]
I'm trying this app since two days, and it stopped recording twice since then.
I currently use an old Redmi Note 4 (I'll get a phone with better camera soon).

I'm a developer myself, but didn't look at the code yet. But for me the main issue is, that I don't see that the recording has stopped, the UI still shows recording. (Enabled / Disabled buttons).

I Installed the app over F-Droid.

As there is really recent development, I thought I write here first.
Should I use the master (build it myself) and see if there is an improvement? Or what would you recommend?

**Comment by woheller69** [comment]
maybe your os is killing the service.
Or in case of time lapse video, increase the delay for camera initialization.
If too short there can be crashes.

**Comment by andreasb242** [comment]
Thanks you for your quick reply!
>maybe your os is killing the service.

I forgot to turn off energy saving for the App, even if the App was still running, may the Service was killed?
It's now turned off, and running again, I'll see tomorrow if this worked...

**Comment by woheller69** [comment]
See also https://dontkillmyapp.com/

**Comment by andreasb242** [comment]
Hi
Sorry for the late reply, but it takes some time for Testing. It's stopping again.
I have now additional a Redmi Note 9 Pro, which shows a little different behavior, the app gets closed. (it does not only stop taking photos, the app is not open any more if the phone gets unlocked)
This happens now twice.

I have additional a VNC Server and an SFTP Server running, I configured the power settings the same for all apps, and both are still running.

So for me the next step is now to look at the code, and may debug...
