### ISSUE TITLE
Record calls and audio

### ISSUE THREAD

**Issue by natrius** [woheller69/TimeLapseCamera#3]
Whats that permission for?

**Comment by woheller69** [comment]
There is no permission for recording calls.
Record audio is for recording normal video with sound.

**Comment by woheller69** [comment]
These permissions are requested


    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.RECORD_AUDIO" />
    <uses-permission android:name="android.permission.SCHEDULE_EXACT_ALARM" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE"/>
    <uses-permission android:name="android.permission.ACCESS_NOTIFICATION_POLICY" />

**Comment by natrius** [comment]
![IMG_20221215_154612](https://user-images.githubusercontent.com/7243447/207901396-13434554-bc54-4f50-a417-a97365b5975f.jpg)

Thats what i got asked :)

**Comment by woheller69** [comment]
No idea, maybe a Xiaomi thing. For me it looks like that:

![Screenshot_20221215-164252_Permission controller](https://user-images.githubusercontent.com/68678880/207904475-b8e2c747-13ab-4a61-9c09-7007bbab3ed4.jpg)
