### ISSUE TITLE
Mobile optimized webpage to access REST API

### ISSUE THREAD

**Issue by andreasb242** [woheller69/TimeLapseCamera#31]
I need to add a mobile optimized webpage to the REST API.
It would make the usage much more easy.

I'll do this soon, I think about the following contents:

- State: Running / Not running / Error
- Battery State
- Start / Stop button (with confirm message Box)
- Refresh button (optional auto refresh, as this anyway is not working in Standby I think I leave this for the moment)
- Show the last image, including timestamp.
- Show the Intervall, how many pictures are taken, and when the next picture is taken.

Feel free to add your Ideas! This is what I think I need, and therefore I'll add soon.

**Comment by andreasb242** [comment]
I cannot assign a Ticket to me, because I'm not part of the Project... I'll work on it anyway.

**Comment by woheller69** [comment]
videos should be handled in similar way, e.g last video including time stamp

How will it work? You load the webpage in a browser an the webpage will then request data via the REST API?

**Comment by andreasb242** [comment]
>videos should be handled in similar way, e.g last video including time stamp

I didn't have a look at video yet. I try always to write code which is extendible. This is probably an additional step.
Maybe in Video recording mode the last picture should be kept in RAM, so we can access it over the REST API?
But this is a later Task.

>How will it work? You load the webpage in a browser an the webpage will then request data via the REST API?

I plan to create a single page webpage, which can be accessed over the REST API. (So this page is included in the App)
This page uses the REST Interface (in .js).
So it will work if you have two mobile phones in the same WiFi network.

I'll create this page now, in a new branch. I'll create a separate pull (based on the last one - you have to merge them in the right order, to see the diffs correctly).

**Comment by woheller69** [comment]
The latest video should at least be listed with name/time stamp, a preview is not mandatory in my view

**Comment by andreasb242** [comment]
![grafik](https://github.com/woheller69/TimeLapseCamera/assets/822958/7613a29c-2196-4207-99ec-9109a597bed1)
This is the HTML template without data.

**Comment by woheller69** [comment]
maybe request the recording mode via REST. 
Also show recording mode.
If mode = jpg show interface as it is.
If not jpg skip the image stuff

**Comment by andreasb242** [comment]
OK, I'll add this. I'll now implement the .js Logic and add some data to the REST API (e.g. Battery state is not yet available)

**Comment by woheller69** [comment]
or make 2 webpages. One which is returned in jpg mode and one for video mode
