### ISSUE TITLE
Camera service stopps - REST API still available

### ISSUE THREAD

**Issue by andreasb242** [woheller69/TimeLapseCamera#33]
The REST API is still running, but the Camera Service is not taking pictures anymore :-(
As this is running in the same APP, there is fore sure a possibility to fix this. This is probably an issue with Power settings, but it can be fixed.

**Comment by andreasb242** [comment]
I added a lot of logging, also crash logs etc. and I found out that it's probably a scheduling issue. I therefore add a second class with a different scheduling and try again.

**Comment by woheller69** [comment]
have you tried to increase the initialization delay?

**Comment by andreasb242** [comment]
>have you tried to increase the initialization delay?

Yes, it doesn't matter, especially as this only is used once at the start.
It's not the issue, the delayed task will be stopped at some pictures, about 50 ... 100 pictures.
I thinks I have now a solution, I'm testing now. But I have some side effects which I need to fix....

**Comment by andreasb242** [comment]
I was wrong :-(

The scheduling used the camera callback to schedule the next image.
But there is some (yet unknown) issue with the camera, and the callback doesn't get called anymore.
Also restarting the camera doesn't help to fix the issue.

So my next plan is to abstract the Camera interface, and add a second implementation with Camera2...
This needs to be done anyway to control the different lenses. Then also a mock can be added, which helps debugging...

**Comment by woheller69** [comment]
I think such changes have a higher potential to break something. So I would prefer to finish and release a version with the REST API first and not mix it with camera API changes...

**Comment by andreasb242** [comment]
>So I would prefer to finish and release a version with the REST API first and not mix it with camera API changes...

I created one pull for the REST API, one for HTML Interface (which will get a small update with autorefresh soon, but I think in a new pull).
I don't update this branches anymore, except if you request a change.
So it's your decision when you create a release. And you can review the changes in logical blocks.

**Comment by andreasb242** [comment]
The Issue does not appear on a Samsung Galaxy S8. I still plan to investigate to get also Xiaomi working.

**Comment by andreasb242** [comment]
Nope, also stopping on Samsung, but it works longer until it failes :-(

**Comment by andreasb242** [comment]
@woheller69 do you use the photo mode? Or just always the Video mode?
If you tested the photo mode successfully, can you tell me on which Phone?

**Comment by woheller69** [comment]
I never used jpg for a long time. Usually I use video because it consumes less data

**Comment by woheller69** [comment]
I have several Samsungs and Motorolas

**Comment by andreasb242** [comment]
My camera 2 implementation #39 use a different scheduling, and on stop the reason is shown in the App, so the 'magic' stop should be solved. As this ticket is created by me, I close it now.
