### ISSUE TITLE
[Feature Request] Quick panel trigger

### ISSUE THREAD

**Issue by ae5960e8-a6fc-491f-b252-898ecf59af95** [woheller69/TimeLapseCamera#4]
Hi, I'd like to suggest adding a button for the Android quick panel so the a recording can be triggered quickly. The user would open the panel and the recording would start in the background after tapping the button.

**Comment by woheller69** [comment]
I do not see why this is useful. In order to make a recording you have to place the phone properly, check the preview, zoom, etc

**Comment by ae5960e8-a6fc-491f-b252-898ecf59af95** [comment]
My setup is slightly awkward, when the phone locks it's annoying to unlock because the fingerprint sensor is covered by my stand. It would make starting and stopping recording easier for me, but as you say I'm unsure how many people it would benefit.
