### ISSUE TITLE
No saved photos

### ISSUE THREAD

**Issue by MLBin04** [woheller69/TimeLapseCamera#48]
Installed latest APK on Samsung Galaxy S6 running Android 7.0. Permissions granted for Camera, Mic and Storage. Phone is on wifi, but no SIM card.

App runs. I get the icon in the task bar when "recording", but nothing is saved in the gallery (yes, I'm looking in Gallery > Pictures). I've tried all 3 recording modes, all without success. Also no periodic shutter sound, which might be a clue? The stock camera and another camera app (Open Camera) work fine. 

===

Hours later...I've discovered more. **The app *is* taking pix, but none of my photo gallery apps can find them** unless I restart the phone. Seems the app photos go into the  'internal storage' > Pictures > 'Project Title' folder (not the DCIM folder). I've tried 3 different photo gallery apps - same result. They don't pick up the TimeLapseCamera images unless I restart my phone. Any thoughts?

**Comment by woheller69** [comment]
If your Gallery app does not work just use a file manager and go to Pictures -> TimeLapseCam folder

Probably a bug of the OS or of the gallery apps. The recordings are there. There is nothing I can do about it...
