### ISSUE TITLE
The app does not save videos or photos

### ISSUE THREAD

**Issue by rh88user** [woheller69/TimeLapseCamera#5]
Hi! The app does not save videos or photos on Android 7, on Huawei P9 Lite. The flash works, but when I want to go to the gallery from the app it just says "couldn't find item" and when I manually inspect the gallery with a file explorer, there is no folder or files with the specified Project Title. I have given the app all the permissions it asked for.

**Comment by woheller69** [comment]
you should find the folder in "Pictures"
For me it works with Android 6, 10, 11, 12
I do not have Android 7 for testing...

**Comment by rh88user** [comment]
You are correct, I am sorry I did not catch it anywhere written down it would go into pictures. The videos are in there too. Thank you.
