### ISSUE TITLE
Network access

### ISSUE THREAD

**Issue by davidmef** [woheller69/TimeLapseCamera#55]
According to https://f-droid.org/packages/org.woheller69.TimeLapseCam/ , the application has full network access. What is it for? Can you document it somewhere?

Thanks for your work.

**Comment by woheller69** [comment]
there is a REST API which allows starting/stopping recordings and downloading while recording. So you do not have to touch the device.

**Comment by davidmef** [comment]
Some developers list in the README the sensitive permissions the app requieres explaining why.
You may also list the existence of the REST API there since it is a distinctive feature and implicitly explains why network access is needed in a camera app.
