### ISSUE TITLE
Schedule recording dosn't work

### ISSUE THREAD

**Issue by islam2hamy** [woheller69/TimeLapseCamera#6]
Android : 7.1.2
Os : miui 11.0.2
Phone : redmi 4x
Battery optimization : not optimized
App Auto start : enabled

**Comment by woheller69** [comment]
you need to click on Start

**Comment by islam2hamy** [comment]
It is not auto record?

**Comment by woheller69** [comment]
Please try this
[app-release.apk.zip](https://github.com/woheller69/TimeLapseCamera/files/10840081/app-release.apk.zip)
-uninstall
-remove .zip and install

**Comment by islam2hamy** [comment]
It is now working fine

**Comment by woheller69** [comment]
I made some more changes, there were some bugs.
E.g. if the scheduled time was changed after being activated this was not recognized

Please try again.

[app-release.apk.zip](https://github.com/woheller69/TimeLapseCamera/files/10844950/app-release.apk.zip)

**Comment by islam2hamy** [comment]
working fine

**Comment by woheller69** [comment]
Found another bug. A scheduled recording that was cancelled before start still was started because the alarm timer was not stopped.
-> Another update

[app-release.apk.zip](https://github.com/woheller69/TimeLapseCamera/files/10847989/app-release.apk.zip)

**Comment by islam2hamy** [comment]
working fine
