### ISSUE TITLE
TimeLapseCamera crashes on selecting "Schedule Recording" option

### ISSUE THREAD

**Issue by 7kilobytes** [woheller69/TimeLapseCamera#8]
The TimeLapseCamera (1.1 version) crashes if select "Schedule Recording" option on LOS 19.1 and 20 versions.

Steps to reproduce.
1. Open TimeLapseCamera
2. Navigate to "Schedule Recording" and tick off the checkbox

The issue is reproduced on LOS 19.1 as well.

https://user-images.githubusercontent.com/21251486/224477343-482acee0-96b2-47cd-8788-79a3901c7635.mp4

**Comment by woheller69** [comment]
Set a time first, then check the box. (Workaround)

**Comment by woheller69** [comment]
and ideally try version from #6 (probably also with this bug)

**Comment by 7kilobytes** [comment]
> Set a time first, then check the box. (Workaround)

Yes, I found that if I set date and time first the TimeLapseCamera does not crash. Presumably, some handler with notice message should be displayed in such case?

**Comment by woheller69** [comment]
Will add a toast and fix the exception
